#!/usr/bin/env python3
"""
Builds a LADDER command-line wrapper from LADDER/notebooks/attack-pattern-extraction.ipynb notebook.

python /tmp/build_ladder_cli_from_notebook.py \
  --notebook /opt/LADDER/notebooks/attack-pattern-extraction.ipynb \
  --output /opt/LADDER/attack_pattern/ladder_attack_pattern_cli.py
"""

from __future__ import annotations

import argparse
import json
import re
import stat
import sys
from pathlib import Path
from typing import Iterable, List


START_MARKER = "Map Extracted AttackPatterns to MITRE"
STOP_MARKER = "Print all extracted attack patterns"

# Symbols that exist in the extracted notebook section.
REQUIRED_SNIPPETS = [
    "SentenceTransformer",
    "enterprise-techniques.csv",
    "attack_pattern_dict",
    "def get_embedding(",
    "def get_embedding_distance(",
    "def get_mitre_id(",
    "def remove_consec_newline(",
    "def get_all_attack_patterns(",
]


def _cell_source(cell: dict) -> str:
    # Return a notebook cell's source as  string.
    src = cell.get("source", "")
    if isinstance(src, list):
        return "".join(src)
    if isinstance(src, str):
        return src
    return ""


def _find_section_cells(nb: dict, start_marker: str, stop_marker: str) -> List[str]:
    #Extract code cells between two markdown markers.
    
    in_section = False
    code_cells: List[str] = []

    for cell in nb.get("cells", []):
        src = _cell_source(cell)

        if cell.get("cell_type") == "markdown":
            if start_marker in src:
                in_section = True
                continue
            if in_section and stop_marker in src:
                break

        if in_section and cell.get("cell_type") == "code":
            code_cells.append(src)

    return code_cells


def _drop_notebook_only_lines(src: str) -> str:
    #Remove notebook magics/shell escapes if any appear in selected cells.
    kept = []
    for line in src.splitlines():
        stripped = line.strip()
        if stripped.startswith("!") or stripped.startswith("%"):
            continue
        if "google.colab" in stripped or "drive.mount" in stripped:
            continue
        kept.append(line.rstrip())
    return "\n".join(kept).strip()


def _patch_empty_string_guard(src: str) -> str:
    # Patch LADDER notebook's remove_consec_newline so empty inference output files do not raise IndexError.
    pattern = (
        r"(def\s+remove_consec_newline\s*\(\s*s\s*\)\s*:\s*\n)"
        r"(\s*)ret\s*=\s*s\[0\]"
    )
    replacement = r'\1\2if not s:\n\2    return ""\n\2ret = s[0]'
    patched, count = re.subn(pattern, replacement, src, count=1)
    if count != 1:
        raise RuntimeError(
            "Could not patch remove_consec_newline; upstream notebook structure changed."
        )
    return patched


def _normalize_extracted_code(code_cells: Iterable[str]) -> str:
    
    chunks = []
    for cell_src in code_cells:
        cleaned = _drop_notebook_only_lines(cell_src)
        if cleaned:
            chunks.append(cleaned)

    code = "\n\n".join(chunks).strip()
    if not code:
        raise RuntimeError("No notebook code was extracted.")

    missing = [snippet for snippet in REQUIRED_SNIPPETS if snippet not in code]
    if missing:
        raise RuntimeError(
            "Extracted notebook section did not contain expected LADDER symbols: "
            + ", ".join(missing)
        )

    code = _patch_empty_string_guard(code)
    return code


CLI_TEMPLATE = '''#!/usr/bin/env python3
"""
Generated during Docker build from the upstream LADDER notebook plus
TTP-WorkBench CLI scaffolding.

Do not edit this file directly. Regenerate it with:
    build_ladder_cli_from_notebook.py --notebook <notebook> --output <this file>
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

from tqdm import tqdm

# ---------------------------------------------------------------------------
# Notebook-derived LADDER mapping logic.
# Extracted at Docker build time from the upstream LADDER notebook.
# ---------------------------------------------------------------------------

{extracted_notebook_code}

# ---------------------------------------------------------------------------
# CLI Helpers
# ---------------------------------------------------------------------------


def _resolve_input_and_output(args: argparse.Namespace) -> tuple[Path, Path]:
    if args.test:
        if args.input is not None:
            raise SystemExit("Do not provide input when using --test")
        input_path = Path("test_input")
        output_path = Path(args.output)
    else:
        if args.input is None:
            raise SystemExit("input is required unless --test is used")
        input_path = Path(args.input)
        output_path = Path(args.output)

    if not input_path.exists():
        raise SystemExit(f"input path does not exist: {input_path}")

    return input_path, output_path


def _prepare_inference_input(input_path: Path) -> tuple[Path, bool, bool]:
    """
    inference.py expects --input-doc to be a directory.

    In directory mode, pass the directory through. In single-file mode, stage the file in a temporary directory.
    """
    is_dir_mode = input_path.is_dir()
    is_file_mode = input_path.is_file()

    if not is_dir_mode and not is_file_mode:
        raise SystemExit(f"input must be a file or directory: {input_path}")

    if is_file_mode:
        infer_input_dir = Path("_infer_input")
        if infer_input_dir.exists():
            shutil.rmtree(infer_input_dir)
        infer_input_dir.mkdir(parents=True, exist_ok=True)

        staged = infer_input_dir / input_path.name
        if staged.resolve() != input_path.resolve():
            shutil.copy2(input_path, staged)

        return infer_input_dir, is_file_mode, is_dir_mode

    return input_path, is_file_mode, is_dir_mode


def _run_ladder_inference(input_for_inference: Path, inf_output_dir: Path) -> None:
    #Run upstream LADDER inference.py to extract attack-pattern phrases
    inf_output_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable,
        "inference.py",
        "--entity-extraction-weight=models/entity_ext.pt",
        "--sentence-classification-weight=models/sent_cls.pt",
        f"--input-doc={input_for_inference}",
        f"--save-path={inf_output_dir}",
    ]

    print("running inference.py...", cmd)
    subprocess.run(cmd, check=True)


def _collect_inference_outputs(inf_output_dir: Path) -> list[Path]:
    #Collect text files written by upstream inference.py
    if not inf_output_dir.exists() or not inf_output_dir.is_dir():
        print(f"inference output directory does not exist: {inf_output_dir}")
        return []

    outputs = sorted(p for p in inf_output_dir.rglob("*.txt") if p.is_file())
    print(f"found {len(outputs)} inference output files")
    return outputs


def _write_mapped_outputs(
    inf_outputs: list[Path],
    output_path: Path,
    is_file_mode: bool,
    is_test: bool,
) -> None:
    #Map extracted phrases to ATT&CK technique IDs and write JSON output
    for inf_out in tqdm(inf_outputs, desc="Mapping attack patterns"):
        mapped = get_all_attack_patterns(inf_out)
        payload = {k: [float(v[0]), v[1]] for k, v in mapped.items()}

        out_json = output_path if is_file_mode else output_path / f"{inf_out.stem}.json"
        out_json.parent.mkdir(parents=True, exist_ok=True)

        with open(out_json, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)

        if is_test:
            print(f"--- Mappings for file: {inf_out.name} ---")
            for k, v in mapped.items():
                print(f"{k} {v} {attack_pattern_dict[k][0][0]}")


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Run LADDER attack-pattern inference and map outputs to ATT&CK IDs"
    )
    ap.add_argument(
        "input",
        nargs="?",
        default=None,
        help="Path to a .txt file or a directory of .txt files",
    )
    ap.add_argument(
        "--output",
        "-o",
        default="mapped_out.json",
        help="Output JSON file in single-file mode, or output directory in directory mode",
    )
    ap.add_argument(
        "--test",
        action="store_true",
        help="Run the upstream notebook-style test case using test_input/",
    )
    args = ap.parse_args()

    input_path, output_path = _resolve_input_and_output(args)

    is_dir_mode = input_path.is_dir()
    is_file_mode = input_path.is_file()

    if is_dir_mode:
        output_path.mkdir(parents=True, exist_ok=True)
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)

    input_for_inference, is_file_mode, _ = _prepare_inference_input(input_path)

    inf_output_dir = Path("notebook_inference_output" if args.test else "output_inference")
    if not args.test and inf_output_dir.exists():
        shutil.rmtree(inf_output_dir)

    _run_ladder_inference(input_for_inference, inf_output_dir)
    inf_outputs = _collect_inference_outputs(inf_output_dir)
    _write_mapped_outputs(inf_outputs, output_path, is_file_mode, args.test)


if __name__ == "__main__":
    main()
'''


def build_cli(notebook: Path, output: Path) -> None:
    nb = json.loads(notebook.read_text(encoding="utf-8"))
    code_cells = _find_section_cells(nb, START_MARKER, STOP_MARKER)
    if not code_cells:
        raise RuntimeError(
            f"No code cells found between markdown markers {START_MARKER!r} and {STOP_MARKER!r}."
        )

    extracted_code = _normalize_extracted_code(code_cells)
    generated = CLI_TEMPLATE.replace("{extracted_notebook_code}", extracted_code)

    # Compile before writing an executable script to catch format/syntax mistakes.
    compile(generated, str(output), "exec")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")

    mode = output.stat().st_mode
    output.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def main() -> None:
    try:
        build_cli("/opt/LADDER/notebooks/attack-pattern-extraction.ipynb", "/opt/LADDER/attack_pattern/ladder_attack_pattern_cli.py")
    except Exception as exc:
        print(f"ERROR: failed to build LADDER CLI: {exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    try:
        build_cli(Path("/opt/LADDER/notebooks/attack-pattern-extraction.ipynb"), Path("/opt/LADDER/attack_pattern/ladder_attack_pattern_cli.py"))
    except Exception as exc:
        print(f"ERROR: failed to build LADDER CLI: {exc}", file=sys.stderr)
        raise

